### PR TITLE
Adds docusaurus site with two doc pages

### PR DESCRIPTION
**Pull request by tamalchowdhury**
I created a new docusarus site with default settings.

I added two pages, a quick intro setup with docker, and another for docker-compose. I copied them directly from the docs folder or Dragonfly repo. I did some minor formatting to both of these pages for better readability.

I also changed the default CSS link color from green to purple.

Please find the instruction to run the site on your local machine by reading the `readme.md` file.

### CODE REVIEW

**Comment by odedponcz** [comment]
I think that we need only the docs. Can you please remove the blog?

**Comment by tamalchowdhury** [comment]
Okay, I will remove it. thanks.

**Comment by tamalchowdhury** [comment]
Removed the blog and the sample docusaurus doc pages.

**Comment by tamalchowdhury** [comment]
Hi @odedponcz can you have a look at these conflicts?

**Comment by romange** [comment]
@odedponcz  should we close this?

**Pull request closed without merging**
